// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Event documents
 */
interface EventDocumentData {
	/**
	 * Title field in *Event*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: event.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Image field in *Event*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: event.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<"sm">;

	/**
	 * Body field in *Event*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: event.body
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * Date field in *Event*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: event.date
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#date
	 */
	date: prismic.DateField;
}

/**
 * Event document from Prismic
 *
 * - **API ID**: `event`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithUID<Simplify<EventDocumentData>, "event", Lang>;

/**
 * Item in *Footer → Quick Links*
 */
export interface FooterDocumentDataQuickLinksItem {
	/**
	 * Title field in *Footer → Quick Links*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.quick_links[].title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Link field in *Footer → Quick Links*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.quick_links[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Item in *Footer → Socials*
 */
export interface FooterDocumentDataSocialsItem {
	/**
	 * Logo field in *Footer → Socials*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.socials[].logo
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	logo: prismic.ImageField<never>;

	/**
	 * Link field in *Footer → Socials*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.socials[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
	/**
	 * Quick Links field in *Footer*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.quick_links[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	quick_links: prismic.GroupField<Simplify<FooterDocumentDataQuickLinksItem>>;

	/**
	 * Body field in *Footer*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.body
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * Socials field in *Footer*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.socials[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	socials: prismic.GroupField<Simplify<FooterDocumentDataSocialsItem>>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<
		Simplify<FooterDocumentData>,
		"footer",
		Lang
	>;

type HomeDocumentDataSlicesSlice = FeatureBlockSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
	/**
	 * Slice Zone field in *Home*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
	 * Meta Description field in *Home*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: home.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Home*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;

	/**
	 * Meta Title field in *Home*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: home.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Content for Map Frame documents
 */
interface MapFrameDocumentData {
	/**
	 * Embed Link field in *Map Frame*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: map_frame.embed_link
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	embed_link: prismic.LinkField;
}

/**
 * Map Frame document from Prismic
 *
 * - **API ID**: `map_frame`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MapFrameDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithUID<
		Simplify<MapFrameDocumentData>,
		"map_frame",
		Lang
	>;

/**
 * Item in *Nav → Items*
 */
export interface NavDocumentDataItemsItem {
	/**
	 * Title field in *Nav → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nav.items[].title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Link field in *Nav → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nav.items[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Content for Nav documents
 */
interface NavDocumentData {
	/**
	 * Logo field in *Nav*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nav.logo
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	logo: prismic.ImageField<never>;

	/**
	 * Items field in *Nav*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nav.items[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<NavDocumentDataItemsItem>>;
}

/**
 * Nav document from Prismic
 *
 * - **API ID**: `nav`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<Simplify<NavDocumentData>, "nav", Lang>;

/**
 * Item in *Slideshow Frame → Images*
 */
export interface SlideshowFrameDocumentDataImagesItem {
	/**
	 * Image field in *Slideshow Frame → Images*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: slideshow_frame.images[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<"small">;
}

/**
 * Content for Slideshow Frame documents
 */
interface SlideshowFrameDocumentData {
	/**
	 * Images field in *Slideshow Frame*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: slideshow_frame.images[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	images: prismic.GroupField<Simplify<SlideshowFrameDocumentDataImagesItem>>;
}

/**
 * Slideshow Frame document from Prismic
 *
 * - **API ID**: `slideshow_frame`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SlideshowFrameDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithUID<
		Simplify<SlideshowFrameDocumentData>,
		"slideshow_frame",
		Lang
	>;

/**
 * Content for Still Frame documents
 */
interface StillFrameDocumentData {
	/**
	 * Image field in *Still Frame*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: still_frame.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<"small">;
}

/**
 * Still Frame document from Prismic
 *
 * - **API ID**: `still_frame`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type StillFrameDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithUID<
		Simplify<StillFrameDocumentData>,
		"still_frame",
		Lang
	>;

/**
 * Content for Stop Motion Frame documents
 */
interface StopMotionFrameDocumentData {
	/**
	 * Video field in *Stop Motion Frame*
	 *
	 * - **Field Type**: Link to Media
	 * - **Placeholder**: *None*
	 * - **API ID Path**: stop_motion_frame.video
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	video: prismic.LinkToMediaField;

	/**
	 * Frames Per Second field in *Stop Motion Frame*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: stop_motion_frame.frames_per_second
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	frames_per_second: prismic.NumberField;
}

/**
 * Stop Motion Frame document from Prismic
 *
 * - **API ID**: `stop_motion_frame`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type StopMotionFrameDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithUID<
		Simplify<StopMotionFrameDocumentData>,
		"stop_motion_frame",
		Lang
	>;

/**
 * Content for Theme documents
 */
interface ThemeDocumentData {
	/**
	 * Background Color field in *Theme*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: theme.background_color
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	background_color: prismic.ColorField;

	/**
	 * Text Color field in *Theme*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: theme.text_color
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#color
	 */
	text_color: prismic.ColorField;
}

/**
 * Theme document from Prismic
 *
 * - **API ID**: `theme`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ThemeDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithUID<Simplify<ThemeDocumentData>, "theme", Lang>;

export type AllDocumentTypes =
	| EventDocument
	| FooterDocument
	| HomeDocument
	| MapFrameDocument
	| NavDocument
	| SlideshowFrameDocument
	| StillFrameDocument
	| StopMotionFrameDocument
	| ThemeDocument;

/**
 * Primary content in *FeatureBlock → Primary*
 */
export interface FeatureBlockSliceDefaultPrimary {
	/**
	 * Theme field in *FeatureBlock → Primary*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_block.primary.theme
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	theme: prismic.ContentRelationshipField<"theme">;

	/**
	 * Title field in *FeatureBlock → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_block.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Body field in *FeatureBlock → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_block.primary.body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body: prismic.RichTextField;

	/**
	 * Frame field in *FeatureBlock → Primary*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_block.primary.frame
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	frame: prismic.ContentRelationshipField<
		"map_frame" | "slideshow_frame" | "still_frame" | "stop_motion_frame"
	>;

	/**
	 * Text Over Image field in *FeatureBlock → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: feature_block.primary.text_over_image
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	text_over_image: prismic.BooleanField;
}

/**
 * Primary content in *FeatureBlock → Items*
 */
export interface FeatureBlockSliceDefaultItem {
	/**
	 * Button Title field in *FeatureBlock → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_block.items[].button_title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	button_title: prismic.KeyTextField;

	/**
	 * Button Theme field in *FeatureBlock → Items*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_block.items[].button_theme
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	button_theme: prismic.ContentRelationshipField<"theme">;

	/**
	 * Button Link field in *FeatureBlock → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_block.items[].button_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	button_link: prismic.LinkField;
}

/**
 * Default variation for FeatureBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureBlockSliceDefault = prismic.SharedSliceVariation<
	"default",
	Simplify<FeatureBlockSliceDefaultPrimary>,
	Simplify<FeatureBlockSliceDefaultItem>
>;

/**
 * Primary content in *FeatureBlock → Primary*
 */
export interface FeatureBlockSliceEventPrimary {
	/**
	 * Theme field in *FeatureBlock → Primary*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_block.primary.theme
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	theme: prismic.ContentRelationshipField<"theme">;

	/**
	 * Title field in *FeatureBlock → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_block.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Event field in *FeatureBlock → Primary*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_block.primary.event
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	event: prismic.ContentRelationshipField<"event">;
}

/**
 * Event variation for FeatureBlock Slice
 *
 * - **API ID**: `event`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureBlockSliceEvent = prismic.SharedSliceVariation<
	"event",
	Simplify<FeatureBlockSliceEventPrimary>,
	never
>;

/**
 * Slice variation for *FeatureBlock*
 */
type FeatureBlockSliceVariation =
	| FeatureBlockSliceDefault
	| FeatureBlockSliceEvent;

/**
 * FeatureBlock Shared Slice
 *
 * - **API ID**: `feature_block`
 * - **Description**: FeatureBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureBlockSlice = prismic.SharedSlice<
	"feature_block",
	FeatureBlockSliceVariation
>;

declare module "@prismicio/client" {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig,
		): prismic.Client<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			EventDocument,
			EventDocumentData,
			FooterDocument,
			FooterDocumentData,
			FooterDocumentDataQuickLinksItem,
			FooterDocumentDataSocialsItem,
			HomeDocument,
			HomeDocumentData,
			HomeDocumentDataSlicesSlice,
			MapFrameDocument,
			MapFrameDocumentData,
			NavDocument,
			NavDocumentData,
			NavDocumentDataItemsItem,
			SlideshowFrameDocument,
			SlideshowFrameDocumentData,
			SlideshowFrameDocumentDataImagesItem,
			StillFrameDocument,
			StillFrameDocumentData,
			StopMotionFrameDocument,
			StopMotionFrameDocumentData,
			ThemeDocument,
			ThemeDocumentData,
			AllDocumentTypes,
			FeatureBlockSlice,
			FeatureBlockSliceDefaultPrimary,
			FeatureBlockSliceDefaultItem,
			FeatureBlockSliceEventPrimary,
			FeatureBlockSliceVariation,
			FeatureBlockSliceDefault,
			FeatureBlockSliceEvent,
		};
	}
}
